import Head from "next/head";
import Image from "next/image";
import React, { useState, useEffect, useCallback } from "react";
import { Button, Input, InputGroup, InputGroupText } from "reactstrap";
import Header from "../../components/Header/Header";
import styles from "./Messages.module.css";
import Search from "../../images/Search-grey.svg";
import defaultAvatar from "../../images/defaultAvatar.png";
import avtar1 from "../../images/avatar1.jpg";
import avtar2 from "../../images/avatar2.jpg";
import avtar3 from "../../images/avatar3.jpg";
import avtar4 from "../../images/avatar4.jpg";
import avtar5 from "../../images/avatar5.jpg";
import avtar6 from "../../images/avatar6.jpg";
import View from "../../images/eye.svg";
import Clip from "../../images/clip.svg"
import Export from "../../images/export.svg"
import Send from "../../images/send-2.svg"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChevronLeft } from '@fortawesome/free-solid-svg-icons';

const contactList = [
    {
        id: 1,
        name: 'Lilly Cardenas',
        email: 'lillycardenas@altbox.com',
        profile_image: avtar1,
        last_message_time: '3 hrs',
        unread_messages: 2,
        is_active: true
    },
    {
        id: 2,
        name: 'Melody Macy',
        email: 'melodymacy@altbox.com',
        profile_image: avtar3,
        last_message_time: '3 hrs',
        unread_messages: 5,
        is_active: true
    },
    {
        id: 3,
        name: 'Ariel Dorsey',
        email: 'arieldorsey@altbox.com',
        profile_image: avtar2,
        last_message_time: '2 hrs',
        unread_messages: 4,
        is_active: false
    },
    {
        id: 4,
        name: 'Jonathon Page',
        email: 'jonathonpage@altbox.com',
        profile_image: avtar4,
        last_message_time: '1 hrs',
        unread_messages: 6,
        is_active: true
    },
    {
        id: 5,
        name: 'Amari Vance',
        email: 'amarivance@altbox.com',
        profile_image: avtar5,
        last_message_time: '1 hrs',
        unread_messages: 4,
        is_active: true
    },
    {
        id: 6,
        name: 'Cristian Tyler',
        email: 'cristiantyler@altbox.com',
        profile_image: avtar6,
        last_message_time: '4 hrs',
        unread_messages: 2,
        is_active: false
    }
]

const checkWidth = (width) => {
    if (width <= 1000) {
        return true;
    }
    return false;
};

const Index = () => {
    const [activeContact, setActiveContact] = useState([]);
    const [showContactList, setShowContactList] = useState(true);
    const [showMessages, setShowMessages] = useState(false);
    const [mobileScreen, setMobileScreen] = useState(true);

    useEffect(() => {
        const isMobile = checkWidth(typeof window !== 'undefined' && (window.innerWidth));
        setMobileScreen(isMobile);
        if (!isMobile && activeContact?.length === 0) {
            setActiveContact(contactList[0]);
        }
        if (!isMobile && !showMessages) {
            setShowMessages(true);
        }
    }, []);

    return (
        <>
            <Head>
                <title>Messages</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className='px-2 px-lg-0'>
                <div className="my-5 container border rounded-20">
                    <div className="row justify-content-start h-666 position-relative">
                        <div className={`${styles.contactList} p-0 ` + (showMessages && !showContactList && mobileScreen ? ' noContacts ' : ' ') + (showMessages && !showContactList && !mobileScreen ? ' w-33 ' : '') + (showContactList && mobileScreen ? ' w-lg-100 ' : '')}>
                            <InputGroup className="p-4 px-3 px-lg-4">
                                <InputGroupText className="bg-white br-none">
                                    <Image src={Search} alt="image" />
                                </InputGroupText>
                                <Input
                                    type="text"
                                    name="searchContact"
                                    placeholder="Search by username or email"
                                    className="form-control h-40 me-1 border-left ps-2 pe-3 br-none"
                                />
                            </InputGroup>
                            {contactList.map((constactItem) => (
                                <div key={constactItem.id} role='button' onClick={() => { setActiveContact(constactItem); setShowMessages(!showMessages); setShowContactList(!showContactList); }} className={'d-flex py-2 px-2 ms-3 ms-lg-3 position-relative justify-content-between align-items-center ' + (activeContact?.id === constactItem.id ? `${styles.activeContact}` : `${styles.normalContact}`)}>
                                    <div className="d-flex align-items-center">
                                        <b></b><b></b>
                                        <div className="w-55 me-3 status">
                                            <Image src={constactItem.profile_image} alt='image' className="rounded-circle" />
                                            <span className={constactItem.is_active ? 'badge-online' : 'badge-offline'}></span>
                                        </div>
                                        <div>
                                            <p className="mb-0 f-16 theme-color axiformaSemiBold">{constactItem.name}</p>
                                            <p className="text-gray f-12 mb-0">{constactItem.email}</p>
                                        </div>
                                    </div>
                                    <div className="me-2">
                                        {activeContact?.id === constactItem.id ?
                                            <span className={"badge " + (`${styles.messageBadge} `)}>{constactItem.unread_messages}</span> :
                                            <span className="text-gray f-12 mb-0 me-2">{constactItem.last_message_time}</span>
                                        }
                                    </div>
                                </div>
                            ))}
                        </div>
                        <div className={`col-lg-8 px-3 px-sm-4 float-end ` + `${styles.messageSide} ` + (!showMessages && showContactList && mobileScreen ? ' noContacts ' : ' ') + (!showMessages && showContactList && !mobileScreen ? ' w-66 ' : ' ') + (showMessages && !showContactList && mobileScreen ? ' w-lg-100 ' : ' ')}>
                            <div className="d-flex justify-content-between align-items-center pt-3 pt-lg-4 pb-2 pb-lg-3 border-bottom ">
                                <div className="d-flex align-items-center ">
                                    <FontAwesomeIcon className={'d-block d-lg-none ' + `${styles.backArrow} `} onClick={() => { setShowContactList(!showContactList); setShowMessages(!showMessages); }} icon={faChevronLeft} />
                                    <div className="ms-2 ms-lg-0">
                                        <p className="mb-0 f-18 theme-color axiformaMedium text-nowrap">{activeContact?.name}</p>
                                        {activeContact?.is_active ?
                                            <p className="mb-0 text-gray f-14 mt-1 d-flex align-items-baseline text-nowrap"><span className="active-now me-1"></span>Active now</p>
                                            : <p className="mb-0 text-gray f-14 mt-1 d-flex align-items-baseline text-nowrap">Not Active</p>}
                                    </div>
                                </div>
                                <div className="d-flex">
                                    <div role="button" className="chat-view d-flex align-item-center justify-content-center me-3 h-40">
                                        <Image src={View} alt="image" />
                                    </div>
                                    <Button className="h-40 py-2  bg-button axiformaMedium">View Project</Button>
                                </div>
                            </div>
                            <div className="sender-viewer">
                                <div className="mt-3 d-flex align-item-center">
                                    <div className="w-55 me-3">
                                        <Image src={activeContact?.profile_image} className="rounded-circle" alt="image" />
                                    </div>
                                    <div className={'chat-sender d-flex align-item-center ' + (`${styles.chatSender}`)}>
                                        <p className="f-14 theme-color mb-0 mx-3">
                                            How likely are you to recommend our company to your friends
                                            and family?
                                        </p>
                                    </div>

                                </div>
                                <div className="mt-3 d-flex align-item-center justify-content-end">
                                    <div className={'chat-sender d-flex align-item-center ' + (`${styles.chatReceiver}`)}>
                                        <p className="f-14 theme-color mb-0 mx-3">
                                            How likely are you to recommend our company to your friends
                                            and family?
                                        </p>
                                    </div>
                                    <div className="w-55 ms-3">
                                        <Image src={defaultAvatar} className="rounded-circle" alt="image" />
                                    </div>
                                </div>
                                <div className="mt-3 d-flex align-item-center">
                                    <div className="w-55 me-3">
                                        <Image src={activeContact?.profile_image} className="rounded-circle" alt="image" />
                                    </div>
                                    <div className={'chat-sender d-flex align-item-center ' + (`${styles.chatSender}`)}>
                                        <p className="f-14 theme-color mb-0 mx-3">
                                            How likely are you to recommend our company to your friends
                                            and family?
                                        </p>
                                    </div>
                                </div>
                                <div className="mt-3 d-flex align-item-center justify-content-end">
                                    <div className={'chat-sender d-flex align-item-center ' + (`${styles.chatReceiver}`)}>
                                        <p className="f-14 theme-color mb-0 mx-3">
                                            How likely are you to recommend our company to your friends
                                            and family?
                                        </p>
                                    </div>
                                    <div className="w-55 ms-3">
                                        <Image src={defaultAvatar} className="rounded-circle" alt="image" />
                                    </div>
                                </div>
                            </div>
                            <div className="border-top mt-3">
                                <InputGroup className="py-2">
                                    <Input
                                        type="text"
                                        placeholder="Type a message..."
                                        className="form-control h-40 border-left py-3 px-0 pe-3 br-none"
                                    />
                                    <InputGroupText className="bg-white br-none" role={'button'}>
                                        <Image src={Clip} alt="image" />
                                    </InputGroupText>
                                    <InputGroupText className="bg-white br-none" role={'button'}>
                                        <Image src={Export} alt="image" />
                                    </InputGroupText>
                                    <InputGroupText className="bg-white br-none pe-0" >
                                        <Button className={'theme-bg-color h-40 d-flex align-item-center ' + (`${styles.sendButton}`)}>
                                            <Image src={Send} alt="image" />
                                        </Button>
                                    </InputGroupText>
                                </InputGroup>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Index;
