import React from "react";
import styles from "./proposal.module.css";
import Head from "next/head";
import Header from "../../components/Header/Header";
import Image from "next/image";
import User from "../../images/user-square.svg";
import Select from "react-select";
import { selectStyles } from "../../constant";
import {
  Button,
  Col,
  Row,
  UncontrolledAccordion,
  AccordionBody,
  AccordionHeader,
  AccordionItem,
  Label,
  Input,
} from "reactstrap";

const Index = () => {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="my-5 container pt-4">
        <div className=" my-2">
          <span className={`mx-2 axiformaSemiBold ${styles.font_color_head}`}>
            Project Inquiries
          </span>
        </div>
        <div className=" border rounded-20 p-4 mb-4">
          <Row>
            <Col
              lg={6}
              className="d-flex align-items-center justify-content-between d-lg-block"
            >
              <p className="f-20 theme-color me-3 me-lg-0 axiformaSemiBold mb-1">
                Customer Details
              </p>
              <Image className="w-30" src={User} alt="image" />
            </Col>
            <Col lg={6} className="mt-2">
              <UncontrolledAccordion defaultOpen={["1", "2", "3"]} stayOpen>
                <AccordionItem>
                  <AccordionHeader targetId="1">
                    <div className="d-flex f-14 justify-content-between align-items-center">
                      <span className="f-14 text-gray axiformaSemiBold d-inline-block w-100 w-lg-50">
                        Customer Personal Details and Budget
                      </span>
                    </div>
                  </AccordionHeader>
                  <AccordionBody accordionId="1">
                    <div className="d-flex justify-content-between">
                      <ul className="p-0">
                        <li className="f-14 text-gray axiformaSemiBold mb-2">
                          Name
                        </li>
                        <li className="f-14 text-gray axiformaSemiBold mb-2">
                          Address
                        </li>
                        <li className="f-14 text-gray axiformaSemiBold mb-2">
                          Contact preference
                        </li>
                        <li className="f-14 text-gray axiformaSemiBold mb-2">
                          Contact Number
                        </li>
                        <li className="f-14 text-gray axiformaSemiBold mb-2">
                          Availability
                        </li>
                        <li className="f-14 text-gray axiformaSemiBold mb-2">
                          Est Budget
                        </li>
                      </ul>
                      <ul className="p-0">
                        <li className="f-14 theme-color axiformaSemiBold mb-2">
                          John Doe
                        </li>
                        <li className="f-14 theme-color axiformaSemiBold mb-2">
                          123, Lorem ipsum dolor, lorem.
                        </li>
                        <li className="f-14 theme-color axiformaSemiBold mb-2">
                          Over Email
                        </li>
                        <li className="f-14 theme-color axiformaSemiBold mb-2">
                          +91 9595959595
                        </li>
                        <li className="f-14 theme-color axiformaSemiBold mb-2">
                          Office Hours
                        </li>
                        <li className="f-14 theme-color axiformaSemiBold mb-2">
                          $32,400
                        </li>
                      </ul>
                    </div>
                  </AccordionBody>
                </AccordionItem>
              </UncontrolledAccordion>
            </Col>
          </Row>
        </div>
        <div className="border container rounded-20 p-40 my-5">
          <div className="mb-3">
            <label className="theme-color f-14  axiformaSemiBold mb-3 d-block">
              Terms
            </label>
          </div>
          <div className="mb-3">
            <label htmlFor="USD20" className="theme-color f-14   mb-3 d-block">
              {" "}
              What is the full amount you'd like to bid for this job?
            </label>
            <input
              type="text"
              name="USD20"
              id="USD20"
              placeholder="USD 20"
              className="w-100 h-40 form-control border text-black focus:outline-none rounded px-3 py-3"
            />
          </div>
          <div className="mb-3">
            <label
              htmlFor="timeline"
              className="theme-color f-14 axiformaSemiBold mb-3 d-block "
            >
              Timeline
            </label>
            <input
              type="text"
              name="timeline"
              id="timeline"
              placeholder="Write here..."
              className="w-100 h-40 border form-control text-black focus:outline-none rounded px-3 py-3"
            />
          </div>
          <div className="mb-3">
            <label
              htmlFor="letter"
              className="theme-color f-14 axiformaSemiBold mb-3 d-block "
            >
              Cover letter
            </label>
            <textarea
              name="letter"
              id="letter"
              cols="10"
              rows="3"
              placeholder="Write here..."
              className="w-100 border form-control text-black focus:outline-none rounded px-3 py-3"
            ></textarea>
          </div>
           
           
            <div class=" mb-3">
              <label
                htmlFor="inputGroupFile02"
                className="theme-color f-14 axiformaSemiBold mb-3 d-block "
              >
                Attachments
              </label>
              <input
                type="file"
                id="inputGroupFile02"
                className={`border form-control text-black focus:outline-none rounded px-3 py-3 ${styles.select_file }`}
              />
            </div>
            <button type="button" className="btn text-white bg-button px-5 h-40 f-14 d-flex justify-content-center align-items-center">Submit</button>
          </div>
        </div>
    </>
  );
};
export default Index;
