import Head from 'next/head';
import React, { useState } from 'react';
import Header from '../../components/Header/Header';
import styles from './dashboard.module.css';
import dynamic from 'next/dynamic'
import Image from 'next/image';
import arrowRightGray from '../../images/arrowRightGray.svg'
import arrowRightBold from '../../images/arrowRightBold.svg'
import mockData from './mockProjectData.json';
import Message from "../../images/message-notif.svg";
import View from "../../images/eye.svg";
import solar from "../../images/solar.png";
import evCharge from "../../images/evCharge.png";
import HVAC from "../../images/HVAC.png";
import electician from "../../images/electrician.png";
import smartMeter from "../../images/smartMeter.png";
import premiumImage from "../../images/premiumImage.png";
import PlatinumLevel from "../../images/PlatinumLevel.png";
import whiteArrow from "../../images/whiteArrow.svg";
import OrderIcon1 from "../../images/OrderIcon1.svg";
import OrderIcon2 from "../../images/OrderIcon2.svg";
const Chart = dynamic(() => import('react-apexcharts'), { ssr: false });

const series = [
    {
        name: 'Inquiries',
        data: [85, 100, 50, 95, 70, 110, 130],
        color: '#002245',
        fontFamily: 'Axiforma Regular'
    },
    {
        name: 'Closing',
        data: [80, 65, 25, 40, 65, 90, 70],
        color: '#69D600'
    }];

const options = {
    chart: {
        type: 'bar',
        height: 350,
        toolbar: {
            show: false,
            tools: {
                download: false,
                reset: false,
                selection: false,
                zoom: false,
                zoomin: false,
                zoomout: false,
                pan: false
            },
        },
    },
    plotOptions: {
        bar: {
            horizontal: false,
            columnWidth: '55%',
            endingShape: 'rounded-full'
        },
    },
    dataLabels: {
        enabled: false
    },
    stroke: {
        show: true,
        width: 2,
        colors: ['transparent']
    },
    xaxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
    },
    yaxis: {
        title: {
            text: ''
        }
    },
    fill: {
        opacity: 1,
        colors: ['#002245', '#69D600']
    },
    tooltip: {
        y: {
            formatter: function (val) {
                return val + " products"
            }
        }
    }
}

const pieChartOptions = {
    dataLabels: {
        enabled: true
    },
    plotOptions: {
        pie: {
            donut: {
                size: "60%",
                labels: {
                    show: true,
                    color: '#69D600',
                    name: {
                        show: true,
                        fontSize: "50px",
                        fontFamily: "Rubik",
                        color: "#69D600",
                        position: 'absolute',
                        left: 0,
                        top: 0,
                        offsetY: -10,
                    },
                    value: {
                        show: true,
                        fontSize: "16px",
                        fontFamily: "Helvetica, Arial, sans-serif",
                        color: undefined,
                        offsetY: 0,
                        formatter: function (val) {
                            return val;
                        }
                    },
                    total: {
                        show: true,
                        label: "Total",
                        color: "#373d3f",
                        formatter: function (w) {
                            return w.globals.seriesTotals.reduce((a, b) => {
                                return a + b;
                            }, 0);
                        }
                    }
                }
            }
        }
    },
    legend: {
        show: true,
        position: "right",
        offsetY: 50,
        height: 210,
    },
    series: [32400, 32400, 32400],
    labels: ['Residential', 'Commercial', 'HVAC'],
    colors: ['#69D600', '#002245', '#EFF1F3'],
    responsive: [{
        breakpoint: 580,
        options: {
            chart: {
                width: 300
            },
            legend: {
                position: 'bottom',
                offsetY: 0,
                height: -30,
            }
        }
    }]
};

const Index = ({ projectData }) => {
    const [activeChart, setActiveChart] = useState('Month');

    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className='px-2 px-lg-0'>
                <div className='mt-4 container'>
                    <div className='row'>
                        <div className='col-lg-6 col-md-12 border p-4 rounded-20'>
                            <div className='d-flex justify-content-between align-items-center'>
                                <div className=''>
                                    <p className='axiformaSemiBold f-20 mb-0 text-nowrap'>Sales Trend</p>
                                    <span className='f-14'>1046 Producst Today</span>
                                </div>
                                <div>
                                    <ul className='d-flex justify-content-start align-items-center'>
                                        <li role='button' onClick={() => setActiveChart('Year')} className={'nav-item h-40 px-2 px-md-3 px-lg-4 py-2 ' + (activeChart === 'Year' ? ` ${styles.activeChartButton}` : null)}>Year</li>
                                        <li role='button' onClick={() => setActiveChart('Month')} className={'nav-item h-40 px-2 px-md-3 px-lg-4 py-2 ' + (activeChart === 'Month' ? ` ${styles.activeChartButton}` : null)}>Month</li>
                                        <li role='button' onClick={() => setActiveChart('Week')} className={'nav-item h-40 px-2 px-md-3 px-lg-4 py-2 ' + (activeChart === 'Week' ? ` ${styles.activeChartButton}` : null)}>Week</li>
                                    </ul>
                                </div>
                            </div>
                            <Chart options={options} series={series} type="bar" className='w-100' height={250} />
                        </div>
                        <div className='col-lg-3 col-md-6 col-12 col mx-0 mx-lg-4 mt-4 me-sm-4 mt-lg-0 border p-4 rounded-20 theme-bg-color text-white'>
                            <div>
                                <div className=''>
                                    <p className='axiformaSemiBold f-20 mb-0'>My Stats</p>
                                </div>
                                <div className='row mt-3'>
                                    <div className='col-6 d-flex flex-column'>
                                        <span className='f-14'>Todays Project</span>
                                        <span className='f-20 axiformaSemiBold'>4</span>
                                    </div>
                                    <div className='col-6 d-flex flex-column px-0'>
                                        <span className='f-14'>This months Project</span>
                                        <span className='f-20 axiformaSemiBold'>173</span>
                                    </div>
                                </div>
                                <div className='row w-100 search px-2 py-2 rounded-2 m-0 mt-4'>
                                    <span role='button' className='d-flex justify-content-between align-items-center'> <span className='f-16'>Go to my projects</span>
                                        <Image src={whiteArrow} alt='image' /></span>
                                </div>
                                <div className='row mt-4 m-0 p-0'>
                                    <div className={`col-6 mb-lg-0 col-sm-6 col-lg-12 col-xl-6 rounded-3 p-2 px-3 ${styles.projectBanner1}`}>
                                        <div className={`${styles.projectImage}`}>
                                            <Image src={OrderIcon1} alt='image' />
                                        </div>
                                        <span className='f-20 theme-color axiformaSemiBold d-block'>300</span>
                                        <span className='f-14 text-gray'>Ongoing Project</span>
                                    </div>
                                    <div className={`col rounded-3 ms-2 ms-lg-0 ms-xl-2 p-2 px-3 pe-2 mt-lg-3 mt-xl-0 ${styles.projectBanner2}`}>
                                        <div className={`${styles.projectImage}`}>
                                            <Image src={OrderIcon2} alt='image' />
                                        </div>
                                        <span className='f-20 theme-color axiformaSemiBold d-block'>300</span>
                                        <span className='f-14 text-gray lh-1'>Completed Project</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='col col-md mt-4 mt-lg-0 border p-4 rounded-20'>
                            <div >
                                <div>
                                    <p className='axiformaSemiBold f-20 mb-0'>Badges</p>
                                    <div className='d-flex flex-column justify-content-center align-items-center w-100 mt-5'>
                                        <Image src={PlatinumLevel} alt='image' />
                                        <span className='mt-3 axiformaSemiBold'>Name</span>
                                        <span className='mt-1'>+91 98989 89898</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className='border container my-4 p-4 rounded-20 w-full'>
                    <div className='d-flex justify-content-between align-items-center'>
                        <span className='axiformaSemiBold f-20'>Inquiries</span>
                        <span className='f-14 d-flex align-items-center' role='button'><span className='me-1'>See all </span><Image src={arrowRightGray} alt='image' /></span>
                    </div>
                    <div className={`${styles.mainInquiries}`}>
                        <div className={`justify-content-start d-inline-flex align-items-center mt-4 ` + `${styles.inquiries}`}>
                            <div className={`card  ` + `${styles.cardItem}`} >
                                <Image src={solar} className="card-img-top" alt="..." />
                                <div className="card-body">
                                    <span className="card-text theme-color fw-semibold">Solar</span>
                                    <div className='d-flex justify-content-between align-items-center'>
                                        <span className='axiformaSemiBold f-20 theme-green'>20</span>
                                        <Image src={arrowRightBold} alt='image' />
                                    </div>
                                </div>
                            </div>
                            <div className={`card ` + `${styles.cardItem}`} >
                                <Image src={evCharge} className="card-img-top" alt="..." />
                                <div className="card-body">
                                    <span className="card-text theme-color fw-semibold">EV charging install</span>
                                    <div className='d-flex justify-content-between align-items-center'>
                                        <span className='axiformaSemiBold f-20 theme-green'>20</span>
                                        <Image src={arrowRightBold} alt='image' />
                                    </div>
                                </div>
                            </div>
                            <div className={`card ` + `${styles.cardItem}`} >
                                <Image src={HVAC} className="card-img-top" alt="..." />
                                <div className="card-body">
                                    <span className="card-text theme-color fw-semibold">HVAC</span>
                                    <div className='d-flex justify-content-between align-items-center'>
                                        <span className='axiformaSemiBold f-20 theme-green'>20</span>
                                        <Image src={arrowRightBold} alt='image' />
                                    </div>
                                </div>
                            </div>
                            <div className={`card ` + `${styles.cardItem}`} >
                                <Image src={electician} className="card-img-top" alt="..." />
                                <div className="card-body">
                                    <span className="card-text theme-color fw-semibold">Electrician General</span>
                                    <div className='d-flex justify-content-between align-items-center'>
                                        <span className='axiformaSemiBold f-20 theme-green'>20</span>
                                        <Image src={arrowRightBold} alt='image' />
                                    </div>
                                </div>
                            </div>
                            <div className={`card ` + `${styles.cardItem}`} >
                                <Image src={smartMeter} className="card-img-top" alt="..." />
                                <div className="card-body">
                                    <span className="card-text theme-color fw-semibold">Smart Meter Install</span>
                                    <div className='d-flex justify-content-between align-items-center'>
                                        <span className='axiformaSemiBold f-20 theme-green'>20</span>
                                        <Image src={arrowRightBold} alt='image' />
                                    </div>
                                </div>
                            </div>
                            <div className={`card ` + `${styles.cardItem}`} >
                                <Image src={smartMeter} className="card-img-top" alt="..." />
                                <div className="card-body">
                                    <span className="card-text theme-color fw-semibold">Smart Meter Install</span>
                                    <div className='d-flex justify-content-between align-items-center'>
                                        <span className='axiformaSemiBold f-20 theme-green'>20</span>
                                        <Image src={arrowRightBold} alt='image' />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className='border container mb-4 p-0 rounded-20 w-full '>
                    <div className='d-flex justify-content-between px-4 pt-4 align-items-center'>
                        <span className='axiformaSemiBold f-20'>Ongoing Projects</span>
                        <span className='f-14 d-flex align-items-center' role='button'><span className='me-1'>See all </span><Image src={arrowRightGray} alt='image' /></span>
                    </div>
                    <div className={`mt-4 table-responsive`}>
                        <table className="table table-hover mt-0">
                            <thead>
                                <tr>
                                    <th className="ps-5 py-3" scope="col">#</th>
                                    <th className="py-3 text-nowrap" scope="col">Name</th>
                                    <th className="py-3 text-nowrap" scope="col">Project Type</th>
                                    <th className="py-3 text-nowrap" scope="col">State</th>
                                    <th className="py-3 text-nowrap" scope="col">Est. Budget</th>
                                    <th className="py-3 text-nowrap" scope="col">Chat</th>
                                    <th className="py-3 text-nowrap" scope="col">Status</th>
                                    <th className="py-3 text-nowrap" scope="col">View Details</th>
                                </tr>
                            </thead>
                            <tbody className={`${styles.projectTable}`}>
                                {projectData.map((project, index) => {
                                    return (
                                        <tr key={project.id} className='align-items-center'>
                                            <td className="ps-5" scope="row">{index + 1}</td>
                                            <td className='text-nowrap'>{project.name}</td>
                                            <td>{project.projectType}</td>
                                            <td>{project.state}</td>
                                            <td>{project.estBudget}</td>
                                            <td><Image src={Message} alt='image' /></td>
                                            {project.status === 'In Progress' ? <td className='text-start'><span className={`px-4 py-2 text-nowrap rounded-2 ` + ` ${styles.progress} ` + ` ${styles.bgProgress} `}>In Progress</span></td> :
                                                project.status === 'Completed' ? <td><span className={`px-4 py-2 rounded-2 ` + ` ${styles.completed} ` + ` ${styles.bgCompleted} `}>Completed</span></td> :
                                                    project.status === 'On Hold' ? <td className='text-start'><span className={`px-4 py-2 rounded-2 ` + ` ${styles.hold} ` + ` ${styles.bgHold} `}>On Hold</span></td> :
                                                        project.status === 'Cancelled' ? <td><span className={`px-4 py-2 rounded-2 ` + ` ${styles.cancelled} ` + ` ${styles.bgCancelled} `}>Cancelled</span></td> :
                                                            project.status === 'Received' ? <td><span className={`px-4 py-2 rounded-2 ` + ` ${styles.received} ` + ` ${styles.bgReceived} `}>Received</span></td> :
                                                                <td>-</td>}
                                            <td><div role='button' className="view d-flex align-item-center justify-content-center"><Image src={View} alt='image' /></div></td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div className='container mb-4'>
                    <div className='row position-relative'>
                        <div className='border container me-0 me-lg-4 mb-4 mb-lg-0 p-4 rounded-20 col-md-12 col-lg-6 h-375'>
                            <div className='d-flex justify-content-between align-items-center'>
                                <span className='axiformaSemiBold f-20'>Earnings</span>
                            </div>
                            <span className='fw-semibold f-16'>This Month</span>
                            <div className='w-100 d-flex justify-content-center align-items-center'>
                                <Chart
                                    options={pieChartOptions}
                                    series={pieChartOptions.series}
                                    type="donut"
                                    width='380'
                                />
                            </div>
                        </div>
                        <div className='border container p-0 rounded-20 col position-relative h-375'>
                            <p className='f-24 theme-color text-center d-block w-100 mt-4 axiformaSemiBold'>Do You need <br /><span className='theme-green'>Premium</span> Service</p>
                            <button type='button' className='f-18 py-2 border-0 rounded-3 text-center text-light mx-auto d-block px-4 theme-bg-color mt-4'>Upgrade Now</button>
                            <div className={`${styles.premiumBaner}`}>
                                <Image src={premiumImage} alt='image' className='text-center d-block mx-auto' ></Image>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export const getServerSideProps = async () => {
    return {
        props: {
            projectData: mockData,
        },
    };
};

export default Index;
